---
# Configuration file source: https://www.youtube.com/watch?v=enhJfb_6KYU&ab_channel=TechWithPat
# Configuration for upload-test
azure_storage_connectionstring: 
downloadTest_container_name: "download-test"
migrationTest_source_container_name: "migration-test-source"
migrationTest_destination_container_name: "migration-test-destination"
uploadTest_container_name: "upload-test"
<<<<<<< HEAD
source_folder_1KB: "C:/Users/durbinju/Desktop/OperatingSystemsProject/source_folder_1KB"
source_folder_1MB: "C:/Users/durbinju/Desktop/OperatingSystemsProject/source_folder_1MB"
source_folder_10MB: "C:/Users/durbinju/Desktop/OperatingSystemsProject/source_folder_10MB"
destination_download_folder: "C:/Users/durbinju/Desktop/OperatingSystemsProject/destination_download_folder"
=======
source_folder_1KB: "C:/Users/tanhe/Desktop/OperatingSystemsProject/source_folder_1KB"
source_folder_1MB: "C:/Users/tanhe/Desktop/OperatingSystemsProject/source_folder_1MB"
source_folder_10MB: "C:/Users/tanhe/Desktop/OperatingSystemsProject/source_folder_10MB"
destination_download_folder: "C:/Users/tanhe/Desktop/OperatingSystemsProject/destination_download_folder"
>>>>>>> d09bd72b7497ccafcc447e46e85ea713d6551afd

