---
# Configuration for Google Cloud storage tests
# Access Keys + region:
Credentials_Dict:
    type: "service_account"
    client_id: "CLIENT_ID"
    client_email: "BACKUP_CLIENT_EMAIL"
    private_key_id: "BACKUP_PRIVATE_KEY_ID"
    private_key: "BACKUP_PRIVATE_KEY"

# Names of buckets to interact with:
downloadTest_bucket_name: "download-test"
migrationTest_source_bucket_name: "migration-test-source"
migrationTest_destination_bucket_name: "migration-test-destination"
uploadTest_bucket_name: "upload-test"

# Paths for surce/destination folders (MAY NEED EDITING)
source_folder_1KB: "/Users/Nicolas Wirth/OneDrive/Documents/GitHub/OperatingSystemsProject/source_folder_1KB"
source_folder_1MB: "/Users/Nicolas Wirth/OneDrive/Documents/GitHub/OperatingSystemsProject/source_folder_1MB"
source_folder_10MB: "/Users/Nicolas Wirth/OneDrive/Documents/GitHub/OperatingSystemsProject/source_folder_10MB"
destination_download_folder: "/Users/Nicolas Wirth/OneDrive/Documents/GitHub/OperatingSystemsProject/destination_download_folder"

