---
# Configuration for AWS storage tests
# Access Keys + region:
aws_access_key_id: "AKIAR34BFXLYDRP6IZWQ"
aws_secret_access_key: "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"
region: "US East (Ohio) us-east-2"

# Names of buckets to interact with:
downloadTest_bucket_name: "henryostestbucket"
migrationTest_source_bucket_name: "migration-test-source"
migrationTest_destination_bucket_name: "migration-test-destination"
uploadTest_bucket_name: "henryostestbucket"

# Paths for surce/destination folders (MAY NEED EDITING)
source_folder_1KB: "C:/Users/tanhe/Desktop/OperatingSystemsProject/source_folder_1KB"
source_folder_1MB: "C:/Users/tanhe/Desktop/OperatingSystemsProject/source_folder_1MB"
source_folder_10MB: "C:/Users/tanhe/Desktop/OperatingSystemsProject/source_folder_10MB"
destination_download_folder: "C:/Users/tanhe/Desktop/OperatingSystemsProject/destination_download_folder"

