---
# Configuration for Google Cloud storage tests
# Access Keys + region:
Credentials_Dict:
    type: "service_account"
    client_id: ""
    client_email: ""
    private_key_id: "1"
    private_key: ""
    project_id: ""
    auth_uri: "https://accounts.google.com/o/oauth2/auth"
    token_uri: "https://oauth2.googleapis.com/token"
    auth_provider_x509_cert_url: "https://www.googleapis.com/oauth2/v1/certs"
    client_x509_cert_url: "https://www.googleapis.com/robot/v1/metadata/x509/395645256631-compute%40developer.gserviceaccount.com"
    
# Names of buckets to interact with:
downloadTest_bucket_name: ""
migrationTest_source_bucket_name: "migration-test-source"
migrationTest_destination_bucket_name: "migration-test-destination"
uploadTest_bucket_name: ""

# Paths for surce/destination folders (MAY NEED EDITING)
source_folder_1KB: "/Users/Nicolas Wirth/OneDrive/Documents/GitHub/OperatingSystemsProject/source_folder_1KB"
source_folder_1MB: "/Users/Nicolas Wirth/OneDrive/Documents/GitHub/OperatingSystemsProject/source_folder_1MB"
source_folder_10MB: "/Users/Nicolas Wirth/OneDrive/Documents/GitHub/OperatingSystemsProject/source_folder_10MB"
destination_download_folder: "/Users/Nicolas Wirth/OneDrive/Documents/GitHub/OperatingSystemsProject/destination_download_folder"

